# Generated by Django 2.2.1 on 2019-05-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
